title: Ape's Blog
email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple

permalink: /:categories/:title
plugins:
  - jekyll-feed

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
# Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tags
  - tags.lock
  - tags.tmp
